### PR TITLE
Added: custom error page for 401 errors

### PR DESCRIPTION
**Pull request by jsilvestre**
Following @frankrousseau's feedback, I set the custom error page for 401 too.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Ok but can we have a stylish message when it fails like the clippy one?

**Comment by jsilvestre** [comment]
DO you mean having a different error? I feel like 401 should be just like 404 for security reason.

**Comment by frankrousseau** [comment]
I mean that currently the displayed error is json.

**Comment by jsilvestre** [comment]
In which case please? ~~There are still raw 401 errors, but I left them on purpose, because I thought they were not user-facing~~. Nevermind, it only show the template if the accept header is set to html, so I can force it everywhere and it will only be displayed where it's relevant. Fixing now.

**Comment by frankrousseau** [comment]
By the way can you return only 404 (for security purpose, it's better to say that it is always a missing page)?

**Pull request merged**
