### PR TITLE
Added: jade precompilation at build time

### PR DESCRIPTION
**Pull request by jsilvestre**
This should speed up the application starting.

Please make sure you tested the PR with the following use case:
* visiting the app in the private area
* visiting the app in the public area (shared folder)
* error 404
* notification emails (share something, upload something in shared folder)

### CODE REVIEW

**Comment by aenario** [comment]
Use express engine option instead of getTemplateExtension : 
https://github.com/cozy/cozy-photos/commit/f8185cb8d0ad5bf9e7226b170a51be777cf8ea8e#diff-0e278c274a1cd63e9c85160d0a67dcaaR23

**Comment by jsilvestre** [comment]
Looks better to me, will do the change.

**Comment by jsilvestre** [comment]
I did the change, but kept the helper because it is needed in the localization_manager, since it's not working like the one in photos (sharing the render function is a good idea though, nice one).

**Comment by frankrousseau** [comment]
Thank you @jsilvestre

**Pull request merged**
