### PR TITLE
Big file list

### PR DESCRIPTION
**Pull request by m4dz**
This PR contains a huge revamp of the Files ViewCollection that improves fluidity and performance for big list of files, using delegation, virtual dom rendering using patch/diff, and Ui improvements.

### CODE REVIEW

**Comment by jsilvestre** [comment]
I asked a few questions to @m4dz, here are the answers so you don't have to ask them again:
## "Can you add comment to the "view proxy" mechanism?"
"I only add a few commits, compared to what is in the PR. Comments are in a latter commit". If you wonder anyway: view proxy is used to listen to the events from the collection view rather than from every single item view. 

## "Why do you use an array + _.find vs an indexed object"
"It might be not intuitive, but it's much faster! Same goes for using _.each over for .. in ..."

**Comment by frankrousseau** [comment]
Thank you @jsilvestre.

So, what is the state of the PR? Need review? Good to merge?

**Comment by m4dz** [comment]
> So, what is the state of the PR? Need review? Good to merge? Work in progress?

Neither one nor another : I need to put in some commits that concern the vdom rendering optimization :wink:

**Comment by frankrousseau** [comment]
Ok thank you @m4dz for the information.

**Comment by frankrousseau** [comment]
I met another user complaining about that problem. This one should go up on the priority list.

**Comment by m4dz** [comment]
Yep, in my todo for next monday :smile:

**Comment by m4dz** [comment]
Oops, I forgot to mention that 11b647a also disable Ui plugins (gallery, preview…) temporary. I'll restore them in later commits :smile:.

**Comment by clochix** [comment]
Refs #223

**Comment by frankrousseau** [comment]
Lots of changes are bieng performed currently on the file list.  I prefer to close this PR. Open a new one when you fill ready to handle the rebase.

**Pull request closed without merging**
