### PR TITLE
Overall design: Quick wins #325

### PR DESCRIPTION
**Pull request by kelukelu**
Enhanced overall design of the Files app.

Here are a few JS development required:
• when you add a folder on a mobile device, the input is larger than the viewport.
• it would be great to remove the hover state on a mobile device. Now we need 2 taps to select an item.

### CODE REVIEW

**Comment by jsilvestre** [comment]
I haven't been able to reproduce first problem. Can you get in touch with me on IRC when you have a moment for that?

About the second one, you actually only need one, but the hover state messes up with the perception of it. I'm pretty sure it's CSS with a media query though (check selector tr.folder-row:hover). Let me know if I have missed something!

Otherwise it looks good, thank you.

**Comment by jsilvestre** [comment]
Thank you for the changes!
I noticed that clicking "kind", "size" or "last mod date" doesn't trigger the sort by the criterion. Is it something you changed?

**Comment by jsilvestre** [comment]
Looks good to me, let's merge!

**Comment by kelukelu** [comment]
It was like that before I worked on it. You can check on your current Files version.

**Comment by kelukelu** [comment]
o/

**Pull request merged**
