### PR TITLE
Display broken files and fix realtime 

### PR DESCRIPTION
**Pull request by frankrousseau**
* If a file has no binary, it's considered as broken.
* During an upload, a file is flagged 'uploading'
* There are more conditions before updating or creating a file model via realtime:
    * not in current folder
    * not in upload queue
    * is not flagged as uploading

### CODE REVIEW

**Comment by aenario** [comment]
@frankrousseau , is this ready to merge (we need to disable huboard or waffle for files, it keeps adding the [in progress] label) ?

**Comment by frankrousseau** [comment]
Yes ready to merge! You can refer to the trello to know if it's ok.

**Comment by aenario** [comment]
everything looks good.
Please build before publish

**Comment by frankrousseau** [comment]
Thank you for the review!

**Pull request merged**
