### PR TITLE
Fix URL for hack/getting-started

### PR DESCRIPTION
**Pull request by eunomie**
Current URL in the README.md display a 404 error.
Language is missing in the URL.

### CODE REVIEW

**Comment by jsilvestre** [comment]
Thank your taking the time to make the change!
Actually the URL has changed to the new doc on https://dev.cozy.io/#set-up-the-development-environment
Would you mind changing it?

**Comment by eunomie** [comment]
Updated!

**Comment by jsilvestre** [comment]
Thank you very much!

**Comment by eunomie** [comment]
You're welcome.

2016-01-05 9:02 GMT+01:00 Joseph Silvestre <notifications@github.com>:

**Pull request merged**
