### PR TITLE
Multiple selection improvements + fix behaviour for folder overwrite

### PR DESCRIPTION
**Pull request by jsilvestre**
Here are the most impactful changes:

* When drag and dropping an existing folder, it caused weird behaviour. Overwriting a folder is a bit tricky, so I did a fix to just prevent it, rather than implementing a whole system to handle it.

* I did multiple changes to the selection of items (see https://github.com/cozy/cozy-files/issues/283):
    * checkboxes are now always visible. It's better for mobile, and users complain they don't find it.
    * the "select all" checkbox now has 3 states: when it's empty, when some items are selected, when all items are selected
    * you can select an item by clicking the line (except if you click one of the action button)

### CODE REVIEW

**Comment by frankrousseau** [comment]
If you change that behavior could you allow to select several files with a shift + click ?

**Comment by jsilvestre** [comment]
The current (in my PR) behaviour is that you select a a file by clicking it. If you click multiple files, it selects them all. I just extended the "checkbox" to the rest of the line.

**Comment by jsilvestre** [comment]
I've just changed the icons of the bulk actions too:
* the same "download" icon than the one used to download a single file.
* a more explicit icon for the move action.

I made the choice after asking the team, I suggested the following changes: https://joseph-silvestre38.cozycloud.cc/apps/files/#folders/e2f72c6a145ac9cc43e3429cb8a80230.

**Comment by jsilvestre** [comment]
I added a fix for https://github.com/cozy/cozy-files/issues/287.

**Comment by jsilvestre** [comment]
@frankrousseau I did what you asked: you can now select multiple items at once, by holding the shift key.

**Comment by frankrousseau** [comment]
I think we should go fast on that one. So, I merge it without making a complete review. A quick review showed that the code is clean. Let the PO review this.

**Comment by frankrousseau** [comment]
@jsilvestre could you push the build?

**Comment by jsilvestre** [comment]
@frankrousseau  Done!

**Pull request merged**
